name: quiz_it
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Monserrat
      fonts:
        #        splash screen
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: quick
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
    - family: quick_bold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
    - family: quick_semi
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
    - family: Quicksand
      fonts:
        - asset:  assets/fonts/Quicksand-VariableFont_wght.ttf
